Añadido  Tablas_Adrian.sql
BetulioMay/DDSI_Practica_3 pull request #1
Opened 2022-12-28 16:30 UTC by adrianldga

2022-12-29 04:39 UTC, BetulioMay requested changes
Cambia el tipo de las fechas de `timestamps` a tipo `date` por consistencia.

2022-12-29 12:03 UTC, adrianldga commented
El create trigger_adrian no lo añadas, los otros dos si. El trigger si puedes probar que no da error, porque yo no puedo probarlo, porque me da error en la ejecucion y he seguido todos los pasos para ejecutarlo.

2022-12-29 23:15 UTC, BetulioMay commented
No puedo "desañadirlo" es merge de todo o nada. Lo que puedes hacer es darle otro nombre como `trigger...TEST.sql` y cuando ya lo tengas listo bien, renombrarlo como antes.

En cuanto al trigger para que lo pruebe, lo probare esta noche, te escribo por aqui lo que me ha salido.

2022-12-29 23:28 UTC, BetulioMay commented
En cuanto a lo del error, yo he tenido un error al compilar mi trigger, algo de que se me caia la conexion o algo asi, deje el link de la solucion que me lo resolvio:
https://github.com/BetulioMay/DDSI_Practica_3/blob/75a9dc3729b052fd639dca57305dfcb8b944a54e/db/db_Cesar.sql#L65
Prueba a ver si ese es tu mismo error y a ver si con lo que he dejado lo puedes resolver.

2022-12-30 01:39 UTC, BetulioMay commented on db/Tablas_Adrian.sql
> +    dni varchar(8) not null,
dni's son varchar(9), 8 digitos y una letra.

2022-12-30 01:59 UTC, BetulioMay requested changes

2022-12-30 01:59 UTC, BetulioMay commented on db/Tablas_Adrian.sql
> +    dni varchar(8) not null,
dni's son varchars de 9, 8 digitos y una letra

2022-12-30 01:59 UTC, BetulioMay commented on db/Tablas_Adrian.sql
> +    dni varchar(8) not null references espectador(dni),
varchar(9)

2022-12-30 01:59 UTC, BetulioMay commented on db/trigger_Adrian.sql
> +  select fecha_pago into fecha from paga p where p.dni = :new.dni;
No usas fecha en ninguna parte del codigo

2022-12-30 01:59 UTC, BetulioMay commented on db/trigger_Adrian.sql
> +  select fecha_pago into fecha from paga p where p.dni = :new.dni;
Si en paga hay un atributo `fecha_pago`, no necesitas `fecha`, es redundante. Remuevelo o usalo en vez de `:new.fecha_pago`.

2022-12-30 01:59 UTC, BetulioMay commented on db/Tablas_Adrian.sql
> + insert into paga values ('1235448', '28/11/2002-20:04:30', '577618');
No funcionará, al insertar el timestamp `fecha_pago` realmente esta insertando una _string_. Usa la función `TO_TIMESTAMP` para todos los inserts de esta manera:

```sql
TO_TIMESTAMP('2002-11-28 20:04:30', 'YYYY-MM-DD HH24:MI:SS')
```

2022-12-30 09:16 UTC, adrianldga commented on db/Tablas_Adrian.sql
> + insert into paga values ('1235448', '28/11/2002-20:04:30', '577618');
No funcionará cunado se realice la inserción (porque a mi me hace una inserccion correcta sin errores) o que a la hora de operar con las fechas, no se realizará de forma correcta?

2022-12-30 09:21 UTC, adrianldga commented
Pero te ha salido un error al ejectar el trigger?, porque yo lo ejecuto en el sqldeveloper y me sale el siguiente error:
Trigger COMPROBARPAGO compilado

LINE/COL  ERROR
--------- -------------------------------------------------------------
9/5       PL/SQL: Statement ignored
9/19      PLS-00382: el tipo de la expresión no es correcto
Errores: comprobar log de compilador

y en la sentencia: 
  cursor pago_comprador is select * from paga p where :new.dni = p.dni;

Pero la sintaxis es correcta y no se si es porque se ha buggeado

2022-12-30 16:24 UTC, BetulioMay commented
Vale ya se lo que pasa. El cursor solo apunta a una tupla de la tabla. En el bloque `DECLARE` no puedes usar `:new`, creo. El cursor debe apuntar a un conjunto de tuplas las cuales quieres comparar con la nueva tupla `:new`.

2022-12-30 16:29 UTC, BetulioMay commented
Ya veo, pues mira dejame probarlo yo a ver, termina las tablas (los cambios me refiero) para que yo pueda testear el trigger y te digo.

2022-12-30 22:49 UTC, BetulioMay commented on db/Tablas_Adrian.sql
> + insert into paga values ('1235448', '28/11/2002-20:04:30', '577618');
Eso no lo se, al menos con los de tipo de `date`, hay que usar la funcion `to_date`. Con timestamps no tengo idea. Pero si no te da errores pues confio.

2022-12-31 02:22 UTC, BetulioMay commented on db/trigger_Adrian.sql
> +    dif_fechas := :new.fecha_pago - regPago.fecha_pago;
`:new.fecha_pago - regPago.fecha_pago` es de tipo `int`, lo cuenta en dias no en `float`.

2022-12-31 16:21 UTC, adrianldga commented on db/trigger_Adrian.sql
> +    dif_fechas := :new.fecha_pago - regPago.fecha_pago;
Pero eso es con date porque solo tiene dias como minima unidad de tiempo, pero con timestamp como tiene horas y todo eso, a lo mejor lo mide en dias, pero si no son dias exactos, pues lo pone como decimal o lo redondea. No lo se

2022-12-31 16:21 UTC, adrianldga commented on db/trigger_Adrian.sql
> +    dif_fechas := :new.fecha_pago - regPago.fecha_pago;
Pero como ahora lo puedo probar voy a ver

2022-12-31 16:26 UTC, BetulioMay commented on db/trigger_Adrian.sql
> +    dif_fechas := :new.fecha_pago - regPago.fecha_pago;
Jode que lío 😅, bueno si ahora lo puedes probar, haz los últimos cambios y ya le hacemos merge

2022-12-31 17:07 UTC, adrianldga commented on db/trigger_Adrian.sql
> +    dif_fechas := :new.fecha_pago - regPago.fecha_pago;
Hay que pasarlo a date primero y ya la resta si sale un float

2022-12-31 17:21 UTC, adrianldga commented
Y he arreglado los errores y no me da error de compilación. (Tendria algo que ver con lo del timestamp porque al cambiarlo, ya no me ha dado error).

2022-12-31 17:21 UTC, adrianldga commented
Ya*

2022-12-31 23:20 UTC, BetulioMay commented
> Y he arreglado los errores y no me da error de compilación. (Tendria algo que ver con lo del timestamp porque al cambiarlo, ya no me ha dado error).

Perfecto, por casualidad tambien has probado que esta bien? Osea pasa los tests?

2023-01-01 15:10 UTC, adrianldga commented
Esta version esta comprobada con sql y el trigger funciona como se espera

2023-01-01 19:31 UTC, BetulioMay commented
Puedes agregar una seccion de tests para el trigger? Asi estaria completo

2023-01-02 04:49 UTC, BetulioMay reviewed
Podrias agregar los tests para el trigger, algunos sencillos, solamente para tenerlos listos de una  para la defensa

2023-01-03 22:13 UTC, mayoras commented
Vale nada se me olvido que ya estaban hechos los test. My bad.
Pues ya hago merge de tu pr y hago la version de las tablas final lo mas pronto posible

2023-01-03 22:13 UTC, merged